# Spec-to-PR Workflow Configuration
# Orchestrates: PM → Architect Context → Security Context → Technical Plan → Editor → Review Loop → PR

name: spec-to-pr
description: "End-to-end workflow from product spec to pull request"
version: "1.0.0"

# Slash command configuration
triggers:
  - "/quick-spec-and-implement"
  - "/quick-spec-and-implement --auto"

# Input modes (detected from arguments)
input_modes:
  user_input: "No arguments - interactive prompt for spec"
  file: "Path to existing spec file (.md)"
  github_issue: "GitHub issue URL"

# Workflow mode
modes:
  interactive:
    description: "Human-in-the-loop at decision points"
    requires_approval: true
    ask_on_unclear: true

  auto:
    description: "Fully autonomous with decision logging"
    requires_approval: false
    ask_on_unclear: false
    confidence_threshold: 0.90
    max_review_iterations: 3

# Agent roles and decision authority
agents:
  orchestrator:
    role: "Main agent - workflow coordination"
    decides: ["workflow progression", "agent handoffs", "escalation"]

  pm:
    role: "Product Manager"
    decides: ["product scope", "acceptance criteria", "priority", "user value"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/pm.md"

  architect:
    role: "Technical Architect"
    decides: ["technical approach", "architecture", "implementation strategy", "tech stack"]
    prompts:
      context: "{ide-invoke-prefix}{ide-folder}/agents/architect.md"
      plan: "{ide-invoke-prefix}{ide-folder}/agents/architect.md"

  security:
    role: "Security Architect"
    decides: ["security requirements", "threat model", "compliance"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/security.md"

  editor:
    role: "Implementation"
    decides: ["code structure", "implementation details"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/editor.md"

  test_engineer:
    role: "Test Writing"
    decides: ["test structure", "test data", "mocking strategy"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/test-engineer.md"

  qa:
    role: "Code Quality Assurance"
    decides: ["code quality", "implementation correctness"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/qa.md"

  test_qa:
    role: "Test Quality Assurance"
    decides: ["test coverage", "test quality", "testing anti-patterns"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/test-qa.md"

  security_qa:
    role: "Security Review"
    decides: ["security compliance", "vulnerability assessment"]
    prompt: "{ide-invoke-prefix}{ide-folder}/agents/security-qa.md"

# Output paths (relative to project root)
paths:
  base: "documentation/task/{epic_id}-EPIC-{epic_name}"
  story: "{base}/US-{story_id}"

  # Artifacts per story
  artifacts:
    spec: "{story}/spec.md"
    technical_context: "{story}/technical-context.md"
    security_context: "{story}/security-addendum.md"
    technical_plan: "{story}/technical-plan.md"
    implementation_log: "{story}/implementation-log.md"
    qa_reviews: "{story}/qa-{review_number}.md"
    test_log: "{story}/test-log.md"
    test_qa_reviews: "{story}/test-qa-{review_number}.md"
    security_reviews: "{story}/security-{review_number}.md"
    decision_log: "{story}/decision-log.md"
    workflow_state: "{story}/workflow-state.yaml"

# Review loop configuration
review_loop:
  max_iterations: 3

  severity_handling:
    blocker:
      action: "must_fix"
      blocks_pr: true
    major:
      action: "should_fix"
      blocks_pr: true
    minor:
      action: "may_fix"
      blocks_pr: false
    nit:
      action: "defer"
      blocks_pr: false

  exit_conditions:
    - "no blockers AND no majors"
    - "max_iterations reached AND human_escalation"

# Step sequence
steps:
  - id: 1
    name: "input-detection"
    file: "steps/step-01-input-detection.md"

  - id: 2
    name: "pm-spec"
    file: "steps/step-02-pm-spec.md"
    agent: "pm"
    output: "spec.md"

  - id: 3
    name: "architect-context"
    file: "steps/step-03-architect-context.md"
    agent: "architect"
    output: "technical-context.md"

  - id: 4
    name: "security-context"
    file: "steps/step-04-security-context.md"
    agent: "security"
    output: "security-addendum.md"

  - id: 5
    name: "architect-plan"
    file: "steps/step-05-architect-plan.md"
    agent: "architect"
    output: "technical-plan.md"

  - id: 6
    name: "editor-implement"
    file: "steps/step-06-editor-implement.md"
    agent: "editor"
    output: "implementation-log.md"

  - id: "6b"
    name: "test-engineer"
    file: "steps/step-06b-test-engineer.md"
    agent: "test_engineer"
    output: "test-log.md"

  - id: 7
    name: "review-loop"
    file: "steps/step-07-review-loop.md"
    agents: ["qa", "test_qa", "security_qa", "editor", "test_engineer"]
    loop: true

  - id: 8
    name: "create-pr"
    file: "steps/step-08-create-pr.md"
    output: "pr_url"
