# Product Spec Workflow Configuration
# Transform idea to product spec through rigorous discovery

name: product-spec
description: "Workflow from idea to product spec through rigorous questioning"
version: "1.0.0"

# Slash command configuration
triggers:
  - "/product-spec"
  - "/product-spec --auto"

# Input modes (detected from arguments)
input_modes:
  user_input: "No arguments - interactive prompt"
  file: "Path to existing notes/idea file"

# Workflow mode
modes:
  interactive:
    description: "Human answers discovery questions"
    requires_approval: true
  auto:
    description: "Autonomous with decision logging"
    requires_approval: false

# Agent roles
agents:
  orchestrator:
    role: "Workflow coordination"

  discovery:
    role: "Product Discovery"
    skills: ["product-discovery"]
    prompt: "{ide-invoke-prefix}{ide-folder}/skills/product-discovery/SKILL.md"

  designer:
    role: "Design Exploration"
    skills: ["brainstorming"]
    prompt: "{ide-invoke-prefix}{ide-folder}/skills/brainstorming/SKILL.md"

# Output paths (relative to project root)
paths:
  base: "documentation/product/specs"
  artifacts:
    discovery: "{base}/discovery-{topic}.md"
    spec: "{base}/spec-{topic}.md"
    workflow_state: "{base}/workflow-state.yaml"
    decision_log: "{base}/decision-log.md"

# Step sequence
steps:
  - id: 1
    name: "input-detection"
    file: "steps/step-01-input-detection.md"

  - id: 2
    name: "product-discovery"
    file: "steps/step-02-product-discovery.md"
    skills: ["product-discovery"]
    output: "discovery-{topic}.md"

  - id: 3
    name: "write-spec"
    file: "steps/step-03-write-spec.md"
    skills: ["brainstorming"]
    output: "spec-{topic}.md"
